# Generated by Django 4.0.6 on 2022-10-01 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='supercategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(blank=True, default='preview/default.jpg', upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('previewimage', models.ImageField(blank=True, default='preview/default.jpg', upload_to='previews')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(blank=True, default='profile/default.jpg', upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previewimage', models.ImageField(blank=True, upload_to='previews')),
                ('targetfile', models.FileField(blank=True, upload_to='media')),
                ('filetype', models.CharField(blank=True, choices=[('audio', 'audio'), ('image', 'image'), ('video', 'video'), ('other', 'other')], max_length=201)),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, default='Kiseu', max_length=200)),
                ('duration', models.CharField(blank=True, default='00:00', max_length=200)),
                ('tags', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, default='0', max_length=200)),
                ('rank', models.CharField(blank=True, max_length=20)),
                ('mainlink', models.URLField(blank=True, default='#')),
                ('youtubelink', models.URLField(blank=True, default='#')),
                ('spotifylink', models.URLField(blank=True, default='#')),
                ('applelink', models.URLField(blank=True, default='#')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subcategory')),
                ('supercategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.supercategory')),
                ('views', models.ManyToManyField(blank=True, related_name='post_views', to='base.ipmodel')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='supercategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supercategory'),
        ),
    ]
