# Generated by Django 4.0.6 on 2022-10-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
