# Generated by Django 4.0.6 on 2022-10-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_ipmodel_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_views', to='base.ipmodel'),
        ),
    ]
