# Generated by Django 4.0.6 on 2022-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_ipmodel_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='ip',
            field=models.CharField(blank=True, default='Kiseu', max_length=100, null=True),
        ),
    ]
