# Generated by Django 4.0.6 on 2022-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_ipmodel_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
