# Generated by Django 4.0.6 on 2022-10-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ipmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmodel',
            name='name',
        ),
    ]
