# Generated by Django 4.0.6 on 2022-10-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_ipmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wavfile',
            field=models.FileField(blank=True, upload_to='wav'),
        ),
    ]
