# Generated by Django 4.0.6 on 2022-10-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_item_wavfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wavfile',
        ),
    ]
