# Generated by Django 4.0.6 on 2022-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/profile/test.jpg', upload_to='profile'),
        ),
    ]
