# Generated by Django 4.0.6 on 2022-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='base.ipmodel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='profile/test.jpg', upload_to='profile'),
        ),
    ]
