# Generated by Django 4.1.1 on 2022-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_objectviewed_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='objectviewed',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
