# Generated by Django 4.1.1 on 2022-10-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_objectviewed_city_objectviewed_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectviewed',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='objectviewed',
            name='country',
        ),
    ]
