# Generated by Django 4.1.1 on 2022-10-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_rename_city_objectviewed_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
